### PR TITLE
Updated about page (updated submission format and re-organized it a bit)

### PR DESCRIPTION
**Pull request by SchwinnL**
Updated the "About" page, please review.
 
- restructured according to the new call page
- updated and shortened the submission instructions

### CODE REVIEW

**Comment by fabianp** [comment]
excellent, thanks! Merged with minor grammatical tweaks

**Comment by fabianp** [comment]
BTW I had to tweak some things, but the call page is now online: https://iclr-blogposts.github.io/2024/call

**Comment by fabianp** [comment]
the about page (https://iclr-blogposts.github.io/2024/about) is not yet online, I'm trying to debug this

**Comment by fabianp** [comment]
clearing the cache fixed the issue.

**Comment by SchwinnL** [comment]
Thanks a lot for the fixes!

**Pull request merged**
