### PR TITLE
Html example blog post

### PR DESCRIPTION
**Pull request by fabianp**
Since I was at it, I also fixed a couple of grammatical errors in the markdown file and added a couple missing entries to the TOC.

### CODE REVIEW

**Comment by fabianp** [comment]
since I was at it I also fixed a couple of grammatical errors in the markdown template and added some missing entries to the TOC

**Comment by fabianp** [comment]
I think this is finally ready. Please take a look @busycalibrating (without urgency)

**Comment by fabianp** [comment]
gentle ping @busycalibrating , as I think its important to have this feature before announcing widely

**Comment by busycalibrating** [comment]
Sorry for the delay, I'll check on this today asap!

**Comment by fabianp** [comment]
Awesome, thanks!

**Comment by busycalibrating** [comment]
Sorry for the delay, but looks great! Thanks you for adding this and for catching those details!

**Pull request merged**
