### PR TITLE
FIX #3 Command ./bin/dockerhub_run.sh fails

### LINKED ISSUE #3: Command ./bin/dockerhub_run.sh fails
I get the error "
```
Could not find gem 'jekyll-target-blank' in locally installed gems
Run `bundle install` to install missing gems.
```

The error message is confusing, as I guess this is an error from docker not having some packages? running locally bundle install doesn't change anything

### PR DESCRIPTION
**Pull request by fabianp**

### CODE REVIEW

**Comment by fabianp** [comment]
ping @busycalibrating :-)

**Comment by busycalibrating** [comment]
Hmm when I test this locally, I still seem to get the error:

```
Could not find jekyll-4.3.2, jekyll-4.3.2, jekyll-scholar-7.1.3, jekyll-scholar-7.1.3, jekyll-target-blank-2.0.2, jekyll-target-blank-2.0.2, mini_racer-0.8.0, mini_racer-0.8.0, webrick-1.8.1, webrick-1.8.1, addressable-2.8.5, addressable-2.8.5, i18n-1.14.1, i18n-1.14.1, rouge-4.1.3, rouge-4.1.3, nokogiri-1.15.4-x86_64-linux, nokogiri-1.15.4-x86_64-linux, mini_mime-1.1.5, mini_mime-1.1.5, loofah-2.21.3, loofah-2.21.3, public_suffix-5.0.3, public_suffix-5.0.3, concurrent-ruby-1.2.2, concurrent-ruby-1.2.2, rexml-3.2.6, rexml-3.2.6, execjs-2.9.1, execjs-2.9.1, racc-1.7.1, racc-1.7.1 in locally installed gems
Run `bundle install` to install missing gems.
```

**Comment by fabianp** [comment]
interesting. Do you get the same error without my "fix"?

**Comment by busycalibrating** [comment]
I get a similar error (needing to run bundle install) but with different packages.

**Comment by fabianp** [comment]
I cleared my docker cache and I can now reproduce the bug

**Comment by fabianp** [comment]
Since the approach of running 

```
./bin/docker_build_image.sh
./bin/docker_run.sh
```

seems to work fine, what do you think of featuring that approach in the instructions and README @busycalibrating  ?

We could also potentially merge both scripts into a single one, I'm not sure why they need to be separate scripts, the second time I call `./bin/docker_build_image.sh` it finishes in less than a second

**Comment by busycalibrating** [comment]
Yeah that sounds good to me! They can be merged I suppose, as they don't seem to be used elsewhere (namely in any of the GH actions)

**Comment by fabianp** [comment]
great! I created a new pull request for that (https://github.com/iclr-blogposts/2024/pull/8)

please review that one instead @busycalibrating and I'll close this one

**Pull request closed without merging**
