### PR TITLE
2024-05-07-clml

### PR DESCRIPTION
**Pull request by BlackHC**
## Checklist before opening a PR

- [x] I am opening a pull request against the `main` branch of the `2024` repo.
- [x] The title of my PR is exactly the name of my markdown file
    - i.e. `_posts/2024-05-07-[SUBMISSION NAME].md` would require a PR name `2024-05-07-[SUBMISSION NAME]` 
- [x] I have **anonymized** my post: my author's list is `Anonymous`, and there is no potential
    content which can reveal my/my collaborators identities.
- [x] My post matches the formatting requirements, including (but not limited to):
    - [x] I have **ONLY MODIFIED** files in the following locations (failure to do so will result in 
        your PR automatically being closed!):
        - a Markdown (or HTML) file in `_posts/` with the format `_posts/2024-05-07-[SUBMISSION NAME].md` (or `.html`)
        - static image assets added to `assets/img/2024-05-07-[SUBMISSION NAME]/`
        - interactive HTML figures added  to `assets/html/2024-05-07-[SUBMISSION NAME]/`
        - citations in a bibtex file in `assets/bibliography/2024-05-07-[SUBMISSION NAME].bib`
    - [x] I have a short 2-3 sentence abstract in the `description` field of my front-matter ([example](https://github.com/iclr-blogposts/2024/blob/295ab5b4c31f2c7d421a4caf41e5481cbb4ad42c/_posts/2024-05-07-distill-example.md?plain=1#L4-L6))
    - [x] I have a table of contents, formatted using the `toc` field of my front-matter ([example](https://github.com/iclr-blogposts/2024/blob/295ab5b4c31f2c7d421a4caf41e5481cbb4ad42c/_posts/2024-05-07-distill-example.md?plain=1#L36-L47))
    - [x] My bibliography is correctly formatted, using a `.bibtex` file as per the sample post

### CODE REVIEW

**Comment by BlackHC** [comment]
Dear Chairs,

I'm sadly not finished with this yet. I'll ping again when it's fully done. Over the weekend 🤞🙏

Thanks so much and apologies for the delay!

Best wishes,
 Andreas

**Comment by fabianp** [comment]
no worries, let me know once you're done! BTW you'll always be able to send PRs to update the post / fix typos 😉

**Comment by BlackHC** [comment]
> no worries, let me know once you're done! BTW you'll always be able to send PRs to update the post / fix typos 😉

Thank you so much! I have pushed a camera-ready now that should be good enough 🤞🙏  It is a big step improvement from the version that was rightly criticized by the reviewers, and I hope the changes address their concerns satisfactorily. I have centered the article more on a comparison between the different possible information-theoretic metrics with a larger background section and added schematic plots and an actual experiment. I might add more but this has been a very time intensive camera-ready project 😅

**Comment by BlackHC** [comment]
PS: I have updated the title and abstract as well, but cannot edit those in OpenReview anymore it seems.

**Comment by fabianp** [comment]
merging, thanks!!!

**Pull request merged**
